modifiers = [
    'semi',
    'demi',
    'super',
    'extra',
    'slight',
    'ultra',
    'xtra'
]

stopwords = [
    'personal use only',
    'personal used',
    'personal use',
    'personal',
    'pro',
    'ot',
    'freeversion',
    'free version',
    'free',
    'demo',
    'svg',
    'el-harrak.blogspot.com : darrati10@gmail.com', # lol -- above 3 label threshold
    'i',
    'ii',
    'iii',
    'iv',
    'v',
    'vi'
    'vii', # encounter no higher roman numerals than 7,
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve' # encounter no higher written number then 12,
    'fonts free',
    'regular',
    'normal'
]

abbreviations = {
    # bold
    'bd': 'bold',
    'bld': 'bold',
    # italic
    'it': 'italic',
    'ita': 'italic',
    'ital': 'italic',
    # semi
    'se': 'semi_',
    'sem': 'semi_',
    # ult
    'ult': 'ultra_',
    # black
    'bk': 'black',
    'blk': 'black',
    # oblique
    'obl': 'oblique',
    # extended
    'ext': 'extended',
    # expanded
    'ex': 'expanded',
    'expand': 'expanded',
    # wide
    'wid': 'wide',
    'wd': 'wide',
    # light
    'lt': 'light',
    'lit': 'light',
    'lgt': 'light',
    # light msc
    'sl': 'super_light',
    'pl': 'paper_light',
    'ul': 'ultra_light',
    # left_italic
    'lefta': 'left_italic',
    'lta': 'left_italic',
    # super
    'su': 'super_',
    'sup': 'super_',
    # hairline
    'hl': 'hairline',
    # extra
    'x': 'extra_',
    # normal
    'norm': 'normal',
    # condensed
    'cn': 'condensed',
    'co': 'condensed',
    'con': 'condensed',
    'cnd': 'condensed',
    'cond': 'condensed',
    'condense': 'condensed',
    'condens': 'condensed',
    # regular
    'rg': 'regular',
    'reg': 'regular',
    # heavy
    'hv': 'heavy',
    # thin
    'thn': 'thin',
    # thick
    'thk': 'thick',
    # small caps
    'sc': 'small_caps',
    # outline
    'ou': 'outline',
    'ol': 'outline',
    'out': 'outline',
    'caps': 'all_caps',
    # extra
    'x': 'extra_',
    'xtra': 'extra_',
    # nonchanging
    'bold': 'bold',
    'italic': 'italic',
    'normal': 'normal',
    'condensed': 'condensed',
    'ultimate': 'ultimate',
    'black': 'black',
    'wide': 'wide',
    'fax': 'fax',
    'ultra_': 'extra_',
    'extra_': 'extra_',
    'xtra_': 'extra_',
    'super_': 'extra_',
    'semi_': 'semi_',
    'demi_': 'semi_',
    'nrw': 'narrow',
    'three_d': 'three_d'
}

unifications = {
    'leftalic': 'left_italic',
    'lefti': 'left_italic',
    'left italic': 'left_italic',
    'leftalic italic': 'left_italic',
    'leftit': 'left_italic',
    'leftita': 'left_italic',
    'left_ital': 'left_italic',
    'left_italic': 'left_italic',
    'extruderight': 'extrude_right',
    'three_d': '3d',
    'ruderight': 'extrude_right',
    'extrude right': 'extrude_right',
    'extrude left': 'extrude_left',
    'extrudeleft': 'extrude_left',
    'rudeleft': 'extrude_left',
    'all caps': 'all_caps',
    'allcaps': 'all_caps',
    'smallcaps': 'small_caps',
    'small caps': 'small_caps',
    ' & ': '_and_',
    'sansserif': 'sans',
    'sans serif': 'sans',
    'sans-serif': 'sans',
    'sans_serif': 'sans',
    'sci fi': 'sci_fi',
    'scifi': 'sci_fi',
    'sci_fi': 'sci_fi',
    'xtra': 'extra',
    'tilt': 'tilted',
    'uppercase': 'all_caps',
    'capital': 'all_caps',
    'brand': 'branding',
    'elegance': 'elegant',
    'adorable': 'cute',
    'logostypes': 'logotype',
    'children': 'kids',
    'child': 'kids',
    'childish': 'kids',
    'young': 'kids',
    'headlines': 'headline',
    'women': 'femenine',
    'woman': 'femenine',
    'men': 'masculine',
    'man': 'masculine',
    'manly': 'masculine',
    'santa': 'christmas',
    'goth': 'gothic',
    'street_art': 'graffiti',
    'technology': 'tech',
    'high_tech': 'tech',
    'techno': 'tech',
    'romance': 'romantic',
    'love': 'romantic',
    'valentines_day': 'romantic',
    'craft': 'arts_and_crafts',
    'crafty': 'arts_and_crafts',
    'minimal': 'minimalist',
    'minimalis': 'minimalist',
    'cowboy': 'wild_west',
    'japan': 'japanese',
    'computers': 'computer',
    'metal': 'hardcore',
    'death_metal': 'hardcore',
    'heavy_metal': 'hardcore',
    '1990s': '90s',
    '1980s': '80s',
    '1970s': '70s',
    '1960s': '60s',
    '1950s': '50s',
    'robotic': 'robot',
    'faux_asian': 'asian',
    'bubbles': 'bubble',
    'bubble_letters': 'bubble',
    'rubber_stamp': 'stamp',
    'girl': 'girly',
    'elementary': 'classroom',
    'kindergarten': 'classroom',
    'football': 'athletic',
    'jersey': 'athletic',
    'american_football': 'athletic',
    'arab': 'arabic',
    'runic': 'runes',
    'goofy': 'silly',
    'cyrillic': 'russian',
    'florist': 'botanical',
    'video_games': 'video_game',
    'games': 'video_games',
    'usa': 'america',
    'slant': 'slanted',
    'slab': 'slab_serif',
    'modern_calligraphy': 'calligraphy',
    'brushpen': 'brush',
    'brush_script': 'brush',
    'lettering': 'hand_lettering',
    'hand_drawn': 'hand_lettering',
    'handmade': 'hand_lettering',
    'hand': 'hand_lettering',
    'block': 'blocky',
    'future': 'futuristic',
    'faux_arabic': 'arabic',
    'islamic': 'arabic',
    'comic_book': 'comic'
}